[graph]
all-features = true

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"

[bans]
multiple-versions = "warn"
wildcards = "deny"

[licenses]
version = 2
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "MIT",
]
